### ISSUE TITLE
missing restream.version.txt

### ISSUE THREAD

**Issue by sulonr** [theyosh/DreamboxReStream#1]
Hi @theyosh!
Very nice project! I like it.
it seems that there in missing file at yours server.
https://theyosh.nl/restream.version.txt
for that i have error message:
Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /var/www/DreamboxReStream/Update.class.php on line 35

maybe you can upload that file here on github and change path to it in Update.class.php file
$lUpdateCheckUrl = 'https://theyosh.nl/restream.version.txt';

Thank you!

**Comment by theyosh** [comment]
Hi,

sorry it is fixed now. I use that file for pushing updates. But this software is a bit 'old' and I do not use it that much. So I missed this.

Should be working again.
