### ISSUE TITLE
Vagrant installation failed 

### ISSUE THREAD

**Issue by mycroft2k** [theyosh/DreamboxReStream#12]
issue on 'vagrant up' 

>DreamboxReStream: Installing dependencies from lock file
>DreamboxReStream: Verifying lock file contents can be installed on current platform.
>DreamboxReStream: Your lock file does not contain a compatible set of packages. Please run composer update.
>DreamboxReStream:
>DreamboxReStream:   Problem 1
>DreamboxReStream: - Root composer.json requires php ^7.3 but your php version (7.2.24) does not satisfy that requirement.
>DreamboxReStream:   Problem 2
>DreamboxReStream: - laravel/framework is locked to version v8.14.0 and an update of this package was not requested.
>DreamboxReStream: - laravel/framework v8.14.0 requires php ^7.3|^8.0 -> your php version (7.2.24) does not satisfy that requirement.
>DreamboxReStream:   Problem 3
>DreamboxReStream: - laravel/ui is locked to version v3.1.0 and an update of this package was not requested.
>DreamboxReStream: - laravel/ui v3.1.0 requires php ^7.3|^8.0 -> your php version (7.2.24) does not satisfy that requirement.
>DreamboxReStream:   Problem 4
>DreamboxReStream: - vemcogroup/laravel-translation is locked to version 3.0.2 and an update of this package was not requested.
>DreamboxReStream: - vemcogroup/laravel-translation 3.0.2 requires php ^7.3 -> your php version (7.2.24) does not satisfy that requirement.
>DreamboxReStream:   Problem 5
>DreamboxReStream: - laravel/framework v8.14.0 requires php ^7.3|^8.0 -> your php version (7.2.24) does not satisfy that requirement.
>DreamboxReStream: - pragmarx/yaml v1.2.1 requires illuminate/support >=5.5.33 -> satisfiable by laravel/framework[v8.14.0].
>DreamboxReStream: - pragmarx/yaml is locked to version v1.2.1 and an update of this package was not requested.
>DreamboxReStream: PHP Warning:  require(/home/vagrant/dreamboxrestream/vendor/autoload.php): failed to open stream: No such file or directory in /home/vagrant/dreamboxrestream/artisan on line 18

can you fix?

thx

**Comment by theyosh** [comment]
Hi, it should be fixed. Do a `git pull` to update the code and rerun vagrant up

**Comment by mycroft2k** [comment]
i see the web interface, but it show on Submit 'Error! Server Error'
![issue_web](https://user-images.githubusercontent.com/6868326/100485907-21b2e580-3102-11eb-8f3f-0698706c942c.JPG)

**Comment by theyosh** [comment]
Could it be that you have an original Dreambox? I am afraid that is not supported (despite the name). As I started 15 years ago with an original Dreambox, I switched to OpenPLI based devices.

This means that your DM should have installed the https://github.com/E2OpenPlugins/e2openplugin-OpenWebif / https://wiki.openpli.org/Webif webinterface.

Do you have '/api/about' on you DM? try: http://10.10.2.80/api/about If that gives a 404 error, I cannot support it.

**Comment by mycroft2k** [comment]
its a DM800se with OpenPLi 4 (2018-09-01-release-4)

http://10.10.2.80/api/about  show this:
> {"info": {"tuners": [{"rec": "", "live": "", "type": "BCM4505 (DVB-S2)", "name": "Tuner A"}], "ifaces": [{"linkspeed": "100 MBit/s", "gw": "10.10.2.1", "friendlynic": "Broadcom STB 10/100 EMAC", "ip": "10.10.2.80", "mac": "00:09:34:2e:5c:b5", "name": "eth0", "v4prefix": 24, "ipv4method": "DHCP", "mask": "255.255.255.0", "ipmethod": "SLAAC", "firstpublic": null, "ipv6": "none/IPv4-only network", "dhcp": true}], "machinebuild": "dm800se", "mem1": "135924 kB", "mem3": "78408 kB free / 135924 kB total", "mem2": "78408 kB", "oever": "PLi-OE", "transcoding": false, "fp_version": 3, "kernelver": "3.2", "kinopoisk": false, "uptime": "6d 0:03", "enigmaver": "2018-09-01-release-4", "driverdate": "3.2-20151201-r7.0.3", "imagever": "4", "friendlychipsetdescription": "Chipset (Frontprocessor Version)", "shares": [], "friendlyimagedistro": "OpenPLi", "brand": "Dream Multimedia", "boxtype": "dm800se", "imagedistro": "openpli", "EX": "", "webifver": "OWIF 1.2.8", "hdd": [{"capacity": "298.1 GB", "labelled_capacity": "320 GB", "friendlycapacity": "260.1 GB free / 298.1 GB (\"320 GB\") total", "mount": "/media/hdd", "free": "260.1 GB", "model": "ATA(WDC WD3200BUCT-6)"}], "chipset": "unknown", "model": "DM800se", "friendlychipsettext": "unknown (3)"}, "service": {"onid": 0, "txtpid": "N/A", "pmtpid": 0, "name": "", "tsid": 0, "pcrpid": 0, "sid": 0, "namespace": "", "height": 0, "apid": 0, "width": 0, "result": false, "aspect": 0, "provider": "", "ref": "", "vpid": 0, "iswidescreen": false}}

i have change the php.ini
'allow_url_include = Off' to On

i see the webinterface
![interface](https://user-images.githubusercontent.com/6868326/100526791-8175c300-31cc-11eb-9dd3-bcceed3879dd.JPG)
but unfortunately no stream is started

**Comment by theyosh** [comment]
Hmm, that is strange. I do not need it.

But I have seen some small code issues. So if you could do a `git pull` and just reload in the browser, it should work better
