### ISSUE TITLE
SD Channels in wrong reselution

### ISSUE THREAD

**Issue by SA7BNT** [theyosh/DreamboxReStream#2]
Hallo,

first of all big thanks for your great work.
Next my question. Where can i find the config to edit the resolution for the SD channels??
HD channels are running fine, but the SD has the wrong rresolution. 
See pic.
Another question. 
How can i config this option
`private static $bouqetsFilter = "";`
Greetings
![Bildschirmfoto 2019-04-12 um 13 54 41](https://user-images.githubusercontent.com/35367117/56035629-f744c680-5d2a-11e9-8b48-ef8d3adf66a8.png)

**Comment by theyosh** [comment]
Hi, thanks for noticing.

I did not tested this. So there is a new release which should fix this.

Regards

**Comment by SA7BNT** [comment]
Thanks for fix that so fast. Running fine now. 
Is it possible to run 2 different boxes through 1 VNC server?
Just now im using VU+ 4k running fine but my DB 800SE (OpenATV 6.3) will not connect. Always writing Web Interface fail. What DB OS can you recommand to run DreamboxReStream?

**Comment by theyosh** [comment]
Hi,

first the setting `private static $bouqetsFilter = "";` should just be edited by hand. As this is a special feature from someone in the past. So enter here the bouqet names that you do NOT want to show in my DreamboxRestream

And about the box, I used different types, but I always install https://openpli.org on it. And that will work. And I do only by boxes that support that OS. So no Dreamboxes for me anymore, as those are not supported anymore.

And I do not support multiple boxes for streaming. So, for now only one box.
