### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by SA7BNT** [theyosh/DreamboxReStream#6]
Hey, 
just testing the last commit, but i´m always getting a server error if i want to save the config.
Can you help me figure out why i´m getting that??

Best 
Tim
<img width="961" alt="Bildschirmfoto 2019-10-22 um 21 05 22" src="https://user-images.githubusercontent.com/35367117/67321338-b0246300-f50f-11e9-8719-33bb9e01f21f.png">

**Comment by theyosh** [comment]
Hi,
thanks for testing! Way cool!

I just committed the latest changes. So a new git pull to get the latest code.

I expect that you have followed: https://github.com/theyosh/DreamboxReStream#install-dreambox-restream?

Or did you use the Vagrant setup?

Also this is for me a bit of testing. As this is a new setup that I had not done before. So it could be it will take some time to figure it out.

After the git pull do the following steps again:
- php composer.phar install --no-dev

And did you create the database file restream.sqlite in the folder database ?

**Comment by SA7BNT** [comment]
Ok thanks for your replay, 
here are some info´s

> sa7bnt@owncloud:/var/www/html/tv/DreamboxReStream/database$ ls -lisa
total 112
396559  4 drwxr-xr-x  5 www-data www-data  4096 Oct 22 20:50 .
390962  4 drwxr-xr-x 13 www-data www-data  4096 Oct 22 20:53 ..
396560  4 -rw-r--r--  1 www-data www-data    26 Oct 22 20:35 .gitignore
396561  4 drwxr-xr-x  2 www-data www-data  4096 Oct 22 20:35 factories
396564  4 drwxr-xr-x  2 www-data www-data  4096 Oct 22 20:35 migrations
396940 88 -rw-r--r--  1 www-data www-data 86016 Oct 22 20:50 restream.sqlite
396574  4 drwxr-xr-x  2 www-data www-data  4096 Oct 22 20:35 seeds
sa7bnt@owncloud:/var/www/html/tv/DreamboxReStream/database$ 

I was running the manual install.
git clone your reposity "DreamboxReStream" 
cd to DreamboxReStream" and there I was running this script.
[https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md](url)

After that i run the last of your
[https://github.com/theyosh/DreamboxReStream#install-dreambox-restream](url)

When i finished the hole process i make a sudo chmod -R www-data:www-data /var/www/html/tv/DreamboxReStream

After that i´m at the config page and running in to the issue.

System is Debian 10 (Buster)

> sa7bnt@owncloud:/run/php$ ls
php7.2-fpm.pid	php7.2-fpm.sock  php7.3-fpm.pid  php7.3-fpm.sock
sa7bnt@owncloud:/run/php$ 

> sa7bnt@owncloud:/run/php$ php -v
PHP 7.3.10-1+b1 (cli) (built: Oct 13 2019 23:50:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.10-1+b1, Copyright (c) 1999-2018, by Zend Technologies
sa7bnt@owncloud:/run/php$

**Comment by theyosh** [comment]
Ok, that looks all ok. And I think I found the bug.

So , another `git pull` and then run the command: `php artisan migrate:fresh`

Then you should be able to save your settings and should continue. First time loading will take some time... maybe minutes... so keep it just running. Afterwards it should speed up.

**Comment by SA7BNT** [comment]
Ok one step longer. 
<img width="1321" alt="Bildschirmfoto 2019-10-22 um 23 22 42" src="https://user-images.githubusercontent.com/35367117/67335707-7a3da980-f524-11e9-842a-32c35cd3e343.png">
But now he is loading and loading. 
Im running DreamboxReStream in /var/www/html/tv/DreamboxReStream/
Where can i define that the path is right instead of the root path (/var/www/html/)
If i try to reconfig through About/setup the link i got from there is Domain/dreambox/1/setup instead of Domain/tv/DreamboxReStream/public/index.php/dreambox/1/setup 
Maybe that is the issue??

> sa7bnt@owncloud:~$ ffmpeg -v
ffmpeg version 4.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516

**Comment by theyosh** [comment]
Ah yes. I have tested it only on a subdomain. Not with sub directories. So at the moment your current setup will not work. I have to look into that.

ffmpeg looks good.
