### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by SA7BNT** [theyosh/DreamboxReStream#7]
Hey,

was testing the last commit from yesterday on a Pi3. But im always running in at "403 Forbidden" if i´m try to open /DreamboxReStream/public/

> /var/www/html/DreamboxReStream/*
> all owned by www-data www-data

php -v showing
> PHP 7.3.11-1+0~20191026.48+debian9~1.gbpf71ca0 (cli) (built: Oct 26 2019 14:18:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1+0~20191026.48+debian9~1.gbpf71ca0, Copyright (c) 1999-2018, by Zend Technologies

Also changed php7.2-fpm to 7.3 in /etc/nginx/sites-enabled/dreambox_restream.conf 
> fastcgi_pass unix:/run/php/php7.3-fpm.sock;

whereis php7.3-fpm
> php7: /usr/bin/php7.3 /usr/share/php7.3-mbstring /usr/share/php7.3-json /usr/share/php7.3-sqlite3 /usr/share/php7.3-bcmath /usr/share/php7.3-readline /usr/share/php7.3-intl /usr/share/php7.3-xmlrpc /usr/share/php7.3-pgsql /usr/share/php7.3-zip /usr/share/php7.3-common /usr/share/php7.3-opcache /usr/share/php7.3-xml /usr/share/php7.3-mysql /usr/share/php7.3-imap /usr/share/php7.3-gd

Am i missing something??

Best

**Comment by theyosh** [comment]
Hi,

euh, strange. But let me clarify something first. I do not had much time lately, so I could not do that much on this. But the problem is that at least that my software needs to run on its own subdomain and will not work on a subdirectory. This is due to the chosen framework Laravel.

Then next, the web interface will run on a Pi, but the video transcoding will probably not work smoothly. I have not yet tested it. But even with the hardware GPU I could not get a stable stream out of it.

So that being said, could you post the contents of  /etc/nginx/sites-enabled/dreambox_restream.conf

Because you need to specify the folder 'public' as root in the NGINX configuration.

**Comment by SA7BNT** [comment]
First of all, thanks for your replay.

> But let me clarify something first. I do not had much time lately, so I could not do that much on this. But the problem is that at least that my software needs to run on its own subdomain and will not work on a subdirectory. This is due to the chosen framework Laravel.

I´m clearly understand that, and that's why I wanted to run it on the Pi and then use FFMPEG from another PC (Server) 



> So that being said, could you post the contents of /etc/nginx/sites-enabled/dreambox_restream.conf

pi@raspberrypi:~ $ cat /etc/nginx/sites-enabled/dreambox_restream.conf
server {
         listen 80;
         listen [::]:80 ipv6only=on;

         # Log files for Debugging
         access_log /var/log/nginx/dreambox_restream-access.log;
         error_log /var/log/nginx/dreambox_restream-error.log;

         # Webroot /var/www/html/DreamboxReStream/public;
         root /var/www/html/DreamboxReStream/public;
         index index.php index.html index.htm;

         # Your Domain Name
         server_name **MySubDomain**;

         location / {
                 try_files $uri $uri/ /index.php?$query_string;
         }

         # PHP-FPM Configuration Nginx
         location ~ \.php$ {
                 try_files $uri =404;
                 fastcgi_split_path_info ^(.+\.php)(/.+)$;
                 fastcgi_pass unix:/run/php/php7.3-fpm.sock;
                 fastcgi_index index.php;
                 fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                 include fastcgi_params;
         }
 }
pi@raspberrypi:~ $

**Comment by SA7BNT** [comment]
God morning,
i´m now at commit https://github.com/theyosh/DreamboxReStream/commit/266edf7a32c8dd5a69ae059efd65d76eb33b009f
Webinterface is running without any issues. So it seems that there may be a issue with the last commit. 
Now i will see to figure out how to point the FFMPEG to a different PC in my network. If i´m not wrong this was possible in the old Version. Because as you wrote it is impossible to get a stabile stream with the Pi.

Best
Tim

**Comment by theyosh** [comment]
Hi,

nice you got the interface working. But I am sorry to say that running ffmpeg on a different server will not work. My previous version used VLC, but I switched to ffmpeg so I could have the latest codecs.

So for you, after a lot of thinking I can now only come of with one solution:

1. Use a server with a powerfull cpu. 2 cores at least.
2. Install VirtualBox https://www.virtualbox.org/
3. Install Vagrant https://www.vagrantup.com/downloads.html
4. Clone my software again
5. Run it with `vagrant up`

Choose the right network card if you have multiple ones. It should request an IP through DHCP.

When it is running, you can use `vagrant ssh` to connect to the box and use `ifconfig` to get the right ip. Then on that IP on port 8090 should a webinterface be running.

The final step then could be that you configure your router to do some portforwarding to get the webinterface also working when you are not at home.

So, for now, only with Virtualbox and Vagrant I see it working.... :(

**Comment by SA7BNT** [comment]
Thanks for replay and i will give it a try.

Best
Tim
